/* Signals — timeline app. Data lives in episodes.json (static, regenerated by the pipeline). */
(function () {
  "use strict";

  var VERDICTS = ["OPPORTUNITY", "RISK", "THEME", "NONE"];
  var VERDICT_LABEL = {
    OPPORTUNITY: "Opportunity",
    RISK: "Risk",
    THEME: "Theme",
    NONE: "None"
  };

  var state = { source: "All", verdict: "All" };
  var episodes = [];
  var generatedDate = "";

  function fmtDate(iso) {
    var parts = iso.split("-");
    var months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
    return months[parseInt(parts[1], 10) - 1] + " " + parseInt(parts[2], 10) + ", " + parts[0];
  }

  function esc(s) {
    return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
  }

  function filtered() {
    return episodes.filter(function (e) {
      var okSource = state.source === "All" || e.source === state.source;
      var okVerdict = state.verdict === "All" || e.verdict === state.verdict;
      return okSource && okVerdict;
    });
  }

  function renderMeta() {
    var dates = episodes.map(function (e) { return e.date; }).sort();
    var el = document.getElementById("meta-line");
    el.textContent = episodes.length + " episodes · " + fmtDate(dates[0]) + " – " + fmtDate(dates[dates.length - 1]);
    document.getElementById("updated").textContent =
      "Last updated " + (generatedDate ? fmtDate(generatedDate) : "—") + " · v1 seed data";
  }

  function renderChips() {
    var sources = ["All"].concat(Array.from(new Set(episodes.map(function (e) { return e.source; }))));
    var srcWrap = document.getElementById("source-filters");
    srcWrap.innerHTML = "";
    sources.forEach(function (s) {
      var b = document.createElement("button");
      b.className = "chip" + (state.source === s ? " active" : "");
      b.textContent = s;
      b.addEventListener("click", function () { state.source = s; render(); });
      srcWrap.appendChild(b);
    });

    var vWrap = document.getElementById("verdict-filters");
    vWrap.innerHTML = "";
    ["All"].concat(VERDICTS).forEach(function (v) {
      var b = document.createElement("button");
      b.className = "chip" + (state.verdict === v ? " active" : "");
      b.textContent = v === "All" ? "All" : VERDICT_LABEL[v];
      b.addEventListener("click", function () { state.verdict = v; render(); });
      vWrap.appendChild(b);
    });
  }

  function renderStats(list) {
    var counts = { OPPORTUNITY: 0, RISK: 0, THEME: 0, NONE: 0 };
    list.forEach(function (e) { counts[e.verdict]++; });
    document.getElementById("stats").innerHTML =
      "<strong>" + counts.OPPORTUNITY + "</strong> Opportunity · " +
      "<strong>" + counts.RISK + "</strong> Risk · " +
      "<strong>" + counts.THEME + "</strong> Theme · " +
      "<strong>" + counts.NONE + "</strong> None";
  }

  function renderTimeline(list) {
    var wrap = document.getElementById("timeline");
    wrap.innerHTML = "";
    if (!list.length) {
      var p = document.createElement("p");
      p.className = "empty";
      p.textContent = "No episodes match these filters.";
      wrap.appendChild(p);
      return;
    }
    list.forEach(function (e) {
      var card = document.createElement("article");
      card.className = "card";

      var top = document.createElement("div");
      top.className = "card-top";

      var date = document.createElement("span");
      date.className = "date";
      date.textContent = fmtDate(e.date);
      top.appendChild(date);

      var src = document.createElement("span");
      src.className = "src";
      src.textContent = e.source;
      top.appendChild(src);

      var badge = document.createElement("span");
      badge.className = "badge v-" + e.verdict.toLowerCase();
      badge.textContent = VERDICT_LABEL[e.verdict];
      top.appendChild(badge);

      card.appendChild(top);

      var h2 = document.createElement("h2");
      if (e.url) {
        var a = document.createElement("a");
        a.href = e.url;
        a.target = "_blank";
        a.rel = "noopener";
        a.textContent = e.title;
        h2.appendChild(a);
      } else {
        h2.textContent = e.title;
      }
      card.appendChild(h2);

      var ul = document.createElement("ul");
      e.bullets.forEach(function (b) {
        var li = document.createElement("li");
        li.textContent = b;
        ul.appendChild(li);
      });
      card.appendChild(ul);

      wrap.appendChild(card);
    });
  }

  function render() {
    var list = filtered();
    renderChips();
    renderStats(list);
    renderTimeline(list);
  }

  fetch("episodes.json")
    .then(function (r) { return r.text(); })
    .then(function (text) {
      // episodes.json carries a leading // generated-date comment; strip comment lines.
      var m = text.match(/generated (\d{4}-\d{2}-\d{2})/);
      if (m) generatedDate = m[1];
      episodes = JSON.parse(text.replace(/^\/\/.*$/gm, ""));
      // Newest first.
      episodes.sort(function (a, b) { return b.date < a.date ? -1 : b.date > a.date ? 1 : 0; });
      renderMeta();
      render();
    })
    .catch(function () {
      document.getElementById("timeline").innerHTML =
        '<p class="empty">Could not load episodes.json.</p>';
    });
})();
